apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iamdb-pvc
  namespace: nodc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: oci
  volumeMode: Filesystem
