version: '3.4'

services:
  documentstorageapi:
    image: ${DOCKER_REGISTRY-}documentstorageapi
    build:
      context: .
      dockerfile: src/DocumentStorageApi/Dockerfile

  codelistprovider:
    image: ${DOCKER_REGISTRY-}codelistprovider
    build:
      context: .
      dockerfile: src/CodelistProvider/Dockerfile
    environment:
      DocumentStorageUrl: http://documentstorageapi:80

  iam:
    image: ${DOCKER_REGISTRY-}iam
    build:
      context: .
      dockerfile: src/CodelistProvider/Dockerfile

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    environment:
      DocumentStorageUrl: http://documentstorageapi:80
      CodelistProviderUrl: http://codelistprovider:80
      IAMUrl: http://iam:80
